FROM node:alpine as build
WORKDIR /usr/src/app
COPY package.json ./
RUN npm install --silent
RUN npm build

FROM nginx:alpine
WORKDIR /var/www
COPY --from=build ./build /var/www
COPY /config/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "deamon off;"]