version: '3.7'

services:
  web:
    container_name: spotify_plaintext_web
    build:
      context: ./client/
      dockerfile: Dockerfile
    volumes:
      - './client/:/app'
      - '/client/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
  backend:
    container_name: spotify_plaintext_backend
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=development
